@startuml

package paper <<Aggregate>> {
    class Paper <<Aggregate Root>> {
        id: String
        teacherId: String
        blankQuizIds: List<String>
        update()
        {static} create(): Paper
    }
}

package examination <<Aggregate>>  {

    class Examination <<Aggregate Root>> {
        id: String
        paper: Paper
        {static} create(): Examination
    }

    class "Paper" as p <<Value Object>>{
        id: String
        teacherId: String
        detail: String
    }

    class "BlankQuiz" as b <<Value Object>> {
        id: String
        description: String
        referenceAnswer: String
        score: Int
    }

    Examination "1" *-- "1" p
    p "1" *-- "1...n" b
}

package answerSheet <<Aggregate>> {
    class AnswerSheet <<Aggregate Root>> {
        id: String
        studentId: String
        handIn()
        review()
        {static} create(): AnswerSheet
    }
}

@enduml
